[package]
name = "firza/aethera"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Signal = "sleitnick/signal@1.5.0"
TableUtil = "sleitnick/table-util@1.2.0"
Trove = "sleitnick/trove@0.5.0"
Symbol = "sleitnick/symbol@2.0.1"
bridgenet2 = "ffrostflame/bridgenet2@1.0.0"
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
bytenet = "ffrostflame/bytenet@0.4.5"
Streamable = "sleitnick/streamable@1.2.4"	