return {
    [0] = "MouseButton1",
    [1] = "MouseButton2",
    [2] = "MouseButton3",
    [3] = "MouseWheel",
    [4] = "MouseMovement",
    [7] = "Touch",
    [8] = "Keyboard",
    [9] = "Focus",
    [10] = "Accelerometer",
    [11] = "Gyro",
    [12] = "Gamepad1",
    [13] = "Gamepad2",
    [14] = "Gamepad3",
    [15] = "Gamepad4",
    [16] = "Gamepad5",
    [17] = "Gamepad6",
    [18] = "Gamepad7",
    [19] = "Gamepad8",
    [20] = "TextInput",
    [21] = "InputMethod",
    [22] = "None"
 }